# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.enabledAddons", "langpack-es-AR@thunderbird.mozilla.org:10.0.11,{972ce4c6-7e08-4474-a285-3208198ce6fd}:10.0.12");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"langpack-es-AR@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/icedove/extensions/langpack-es-AR@thunderbird.mozilla.org.xpi\",\"mtime\":1353775196000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/icedove/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1381008131000}}}]");
user_pref("extensions.lastAppVersion", "10.0.12");
user_pref("extensions.lastPlatformVersion", "10.0.12");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "10.0.12");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("toolkit.telemetry.enabled", true);
user_pref("toolkit.telemetry.prompted", true);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
